Repository Hyejinijini/my-react-blog, pull requests merged in 2024-08, with the labels that each got.

#30 add : msw 예제 입니다
  .yarn/install-state.gz
  package.json
  public/mockServiceWorker.js
  src/api/apiClient.js
  src/api/keys/about/url.js
  src/common/hooks/useDataFetchHooks.js
  src/main.jsx
  src/mocks/browser.js
  src/mocks/handlers.js
  src/pages/about/AboutMe.jsx
  src/pages/about/components/UserInfo.jsx
  src/pages/about/hooks/useDataFetchHooks.js
  src/pages/contact/Contact.jsx
  src/pages/home/Home.jsx
  vite.config.js
  yarn.lock
Labels: update

#35 Update: README.md 수정
  README.md
Labels: update

#43 Update: SideBar 수정
  .yarn/src/common/components/SideBar.jsx
Labels: update

#46 Reviews/project review 2
  .eslintrc.cjs
  .yarn/install-state.gz
  src/common/components/NewWrite.jsx
  src/common/components/SideBar.jsx
  src/common/components/etc/Loading.jsx
  src/common/components/etc/MetaTags.jsx
  src/common/components/etc/NotFound.jsx
  src/common/components/footer/CopyRight.jsx
  src/common/components/footer/Footer.jsx
  src/common/components/header/Header.jsx
  src/common/components/header/HeaderList.jsx
  src/common/components/header/OffCanvasLeft.jsx
  src/common/components/sidebar/SideBar.jsx
  src/common/components/sidebar/SideBarForm.jsx
  src/layouts/Layout.jsx
  src/pages/about/About.jsx
  src/pages/about/components/AboutDetail.jsx
  src/pages/home/Home.jsx
  src/pages/home/components/ReadMe.jsx
  src/pages/projects/Projects.jsx
  src/router.jsx
Labels: review

#48 Update: Header 컴포넌트 수정
  src/common/components/header/BlogTitle.jsx
  src/common/components/header/Header.jsx
  src/common/components/header/HeaderList.jsx
  src/common/components/header/Logo.jsx
  src/common/hooks/useDataFetchHooks.js
Labels: update

#49 Update: Header 카테고리명 변경
  src/common/components/header/HeaderList.jsx
  src/pages/about/components/AboutMain.jsx
  src/pages/about/router.jsx
  src/pages/blog/Blog.jsx
  src/pages/blog/components/BlogDetail.jsx
  src/pages/blog/components/BlogHeader.jsx
  src/pages/blog/components/BlogHeaderList.jsx
  src/pages/blog/components/BlogList.jsx
  src/pages/blog/components/BlogMain.jsx
  src/pages/blog/components/BlogSearch.jsx
  src/pages/blog/components/DetailPage.jsx
  src/pages/blog/components/ReadMe.jsx
  src/pages/blog/components/SideBar.jsx
  src/pages/blog/components/SideBarList.jsx
  src/pages/blog/components/UserInfo.jsx
  src/pages/blog/hooks/useDataFetchHooks.js
  src/pages/blog/hooks/useFilteredListHook.js
  src/pages/blog/router.jsx
  src/router.jsx
Labels: update

#50 Delete: projects 폴더 삭제
  src/pages/projects/Projects.jsx
Labels: delete

#51 Update: Header 컴포넌트 수정
  src/common/components/header/CalendarModal.jsx
  src/common/components/header/DropdownButton.jsx
  src/common/components/header/HeaderList.jsx
  src/common/components/header/Logo.jsx
Labels: update

#52 Update: SideBar 컴포넌트 수정
  src/common/components/sidebar/GoToLink.jsx
  src/common/components/sidebar/ProfileDataFetcher.jsx
  src/common/components/sidebar/ProfileImage.jsx
  src/common/components/sidebar/ProfileIntro.jsx
  src/common/components/sidebar/SideBar.jsx
  src/common/components/sidebar/SideBarForm.jsx
Labels: update

#53 Update: SideBar 컴포넌트 수정
  src/common/components/sidebar/SideBar.jsx
  src/common/components/sidebar/SideBarForm.jsx
Labels: update

#54 Update: common 컴포넌트 및 훅 수정
  src/common/components/NewWrite.jsx
  src/common/hooks/useDataFetchHooks.js
  src/router.jsx
Labels: update

#55 Update: Home 컴포넌트 수정
  .yarn/install-state.gz
  src/assets/styles/css/home/intro.module.css
  src/pages/home/Home.jsx
  src/pages/home/components/HomeMain.jsx
  src/pages/home/components/IntroEditBtn.jsx
  src/pages/home/components/IntroEditForm.jsx
  src/pages/home/components/ReadMe.jsx
  src/pages/home/components/SelfIntro.jsx
Labels: update

#56 Update: Home 컴포넌트 수정
  index.html
  package.json
  src/assets/styles/css/index.css
  src/main.jsx
  src/pages/home/components/HomeMain.jsx
  yarn.lock
Labels: update

#57 Update: Home 페이지 수정
  package.json
  src/assets/images/짱구.gif
  src/assets/styles/css/home/intro.module.css
  src/assets/styles/css/home/selfInfo.module.css
  src/pages/home/components/HomeMain.jsx
  src/pages/home/components/InfoBack.jsx
  src/pages/home/components/InfoFront.jsx
  src/pages/home/components/IntroEditBtn.jsx
  src/pages/home/components/IntroEditForm.jsx
  src/pages/home/components/MyInfo.jsx
  src/pages/home/components/SelfIntro.jsx
  src/pages/home/components/TechStack.jsx
  yarn.lock
Labels: update

#58 Update: About 컴포넌트 수정
  src/mocks/handlers.js
  src/pages/blog/Blog.jsx
  src/pages/blog/components/BlogCreate.jsx
  src/pages/blog/components/BlogDetail.jsx
  src/pages/blog/components/BlogList.jsx
  src/pages/blog/components/BlogMain.jsx
  src/pages/blog/components/BlogSearch.jsx
  src/pages/blog/components/SideBar.jsx
  src/pages/blog/components/WriteBtn.jsx
  src/pages/blog/hooks/useFilteredListHook.js
  src/router.jsx
Labels: update

#59 Add: 캘린더 페이지 추가
  package.json
  src/common/components/header/HeaderList.jsx
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/router.jsx
  src/router.jsx
  yarn.lock
Labels: page addition

#61 reviews : project review3
  .yarn/install-state.gz
  src/common/components/header/HeaderList.jsx
  src/common/components/sidebar/ProfileDataFetcher.jsx
  src/common/components/sidebar/SideBar.jsx
  src/common/hooks/useDataFetchHooks.js
  src/pages/blog/components/DetailPage.jsx
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/EventModal.jsx
  src/pages/home/components/InfoBack.jsx
Labels: review

#62 Update: Home 컴포넌트 수정
  src/assets/images/axios-icon.svg
  src/assets/images/react-hook-form-icon.svg
  src/assets/images/storybook-icon.svg
  src/assets/images/zustand-icon.svg
  src/pages/home/components/InfoBack.jsx
  src/pages/home/components/InfoFront.jsx
  src/pages/home/components/TechStack.jsx
Labels: update

#63 Update: Calendar 컴포넌트 수정
  src/assets/styles/css/calendar/calendar.css
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/EditEventModal.jsx
  src/pages/calendar/components/EventList.jsx
  src/pages/calendar/components/EventModal.jsx
  src/pages/calendar/router.jsx
Labels: update

#64 Add: GuestBook 컴포넌트 추가
  src/pages/blog/Blog.jsx
  src/pages/blog/components/BlogCreate.jsx
  src/pages/blog/components/BlogDetail.jsx
  src/pages/blog/components/BlogHeader.jsx
  src/pages/blog/components/BlogHeaderList.jsx
  src/pages/blog/components/BlogList.jsx
  src/pages/blog/components/BlogMain.jsx
  src/pages/blog/components/BlogSearch.jsx
  src/pages/blog/components/DetailPage.jsx
  src/pages/blog/components/ReadMe.jsx
  src/pages/blog/components/SideBar.jsx
  src/pages/blog/components/SideBarList.jsx
  src/pages/blog/components/UserInfo.jsx
  src/pages/blog/components/WriteBtn.jsx
  src/pages/blog/router.jsx
  src/pages/guestbook/Guestbook.jsx
  src/pages/guestbook/components/CommentEditDelete.jsx
  src/pages/guestbook/components/CommentEditForm.jsx
  src/pages/guestbook/components/CommentForm.jsx
  src/pages/guestbook/components/CommentHeader.jsx
  src/pages/guestbook/components/CommentSection.jsx
  src/pages/guestbook/hooks/useComments.js
  src/pages/guestbook/hooks/useDataFetchHooks.js
  src/pages/guestbook/hooks/useFilteredListHook.js
  src/pages/guestbook/router.jsx
Labels: page addition

#65 Update: common 컴포넌트 및 전체 라우팅 수정
  .yarn/install-state.gz
  src/common/components/footer/Footer.jsx
  src/common/components/header/HeaderList.jsx
  src/router.jsx
Labels: update

#66 Update: 스타일 수정
  src/common/components/sidebar/SideBar.jsx
  src/pages/home/components/MyInfo.jsx
Labels: update

#76 Delete: unused files
  src/api/keys/about/url.js
  src/common/components/NewWrite.jsx
  src/common/components/header/CalendarModal.jsx
  src/common/components/header/DropdownButton.jsx
  src/mocks/handlers.js
Labels: delete

#77 Update: Pagination 컴포넌트 수정
  src/common/components/Pagination.jsx
  src/common/components/pagination/NextBtn.jsx
  src/common/components/pagination/PageNumber.jsx
  src/common/components/pagination/Pagination.jsx
  src/common/components/pagination/PreviousBtn.jsx
Labels: update

#78 Update: Guestbook 컴포넌트 수정
  src/pages/guestbook/Guestbook.jsx
  src/pages/guestbook/components/CommentEditDelete.jsx
  src/pages/guestbook/components/CommentEditForm.jsx
  src/pages/guestbook/components/CommentForm.jsx
  src/pages/guestbook/components/CommentHeader.jsx
  src/pages/guestbook/components/CommentSection.jsx
  src/pages/guestbook/hooks/useComments.js
Labels: update

#80 Update: InfoBack.jsx 컴포넌트 수정
  src/common/components/sidebar/SideBarForm.jsx
  src/pages/home/components/InfoBack.jsx
Labels: update

#81 Update: Guestbook 페이지 수정
  src/pages/guestbook/Guestbook.jsx
  src/pages/guestbook/components/CommentEditForm.jsx
  src/pages/guestbook/components/CommentForm.jsx
Labels: update

#82 Update: Calendar 페이지 수정
  src/assets/styles/css/calendar/calendar.css
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/EditBtn.jsx
  src/pages/calendar/components/EditEventForm.jsx
  src/pages/calendar/components/EditEventModal.jsx
  src/pages/calendar/components/EditInputField.jsx
  src/pages/calendar/components/EventBtn.jsx
  src/pages/calendar/components/EventForm.jsx
  src/pages/calendar/components/EventInputField.jsx
  src/pages/calendar/components/EventList.jsx
  src/pages/calendar/components/EventModal.jsx
Labels: update

#84 Update: Home 페이지 수정
  src/pages/home/components/FrontImage.jsx
  src/pages/home/components/FrontIntro.jsx
  src/pages/home/components/InfoBack.jsx
  src/pages/home/components/InfoFront.jsx
  src/pages/home/components/MyInfo.jsx
Labels: update

#85 Update: api URL 경로 수정
  src/api/keys/home/url.js
  src/api/keys/sidebar/url.js
  src/mocks/handlers.js
Labels: update

#86 Update: api import 경로 수정 및 Layout.jsx 컴포넌트 주석 추가
  src/common/components/sidebar/ProfileDataFetcher.jsx
  src/layouts/Layout.jsx
Labels: update

#87 Update: Techstack 컴포넌트 수정
  package.json
  src/pages/home/Home.jsx
  src/pages/home/components/Test.jsx
  yarn.lock
Labels: update

#89 Update: calendar 페이지 수정
  package.json
  src/pages/calendar/Calendar.jsx
  src/pages/calendar/components/EditEventForm.jsx
  src/pages/calendar/components/EditEventModal.jsx
  src/pages/calendar/components/EventForm.jsx
  src/pages/calendar/components/EventModal.jsx
  yarn.lock
Labels: update

#90 Update: home 페이지 수정
  .yarn/install-state.gz
  README.md
  src/pages/home/Home.jsx
  src/pages/home/components/MyInfo.jsx
  src/pages/home/components/Test.jsx
Labels: update

#91 Bug: sidebar 데이터 가져오는 문제 수정
  src/common/components/sidebar/ProfileDataFetcher.jsx
Labels: bug

#92 Udpate: index.css 파일에 react-color 기본 css 추가
  src/assets/styles/css/index.css
Labels: update

#98 Update: SideBar 에서 데이터 가져오는 방식 변경
  src/common/components/sidebar/ProfileDataFetcher.jsx
  src/common/components/sidebar/SideBar.jsx
Labels: update, refactor

#100 Update: storybook 수정
  src/stories/Button.jsx
  src/stories/Button.stories.js
Labels: update

#101 Update: 공통 컴포넌트 일부 Storybook 에 등록
  src/common/components/etc/Loading.jsx
  src/common/components/footer/CopyRight.jsx
  src/common/components/header/BlogTitle.jsx
  src/stories/etc/Loading.stories.js
  src/stories/footer/CopyRight.stories.js
  src/stories/header/BlogTitle.stories.js
Labels: update

#103 Update: HomeMain 스타일 조정
  src/pages/home/components/HomeMain.jsx
Labels: update, styling

#104 Update: Loading 컴포넌트 위치 조정
  src/common/components/etc/Loading.jsx
Labels: update, styling
